### ISSUE TITLE
Netlify build fails when trying to resolve prismjs

### ISSUE THREAD

**Issue by vvirta** [matfantinel/sveltekit-static-blog-template#11]
Disclaimer... This is very likely user error, as I'm not too experienced. I will record it in any case, so that the eventual fix will be visible to others.

I tried to deploy to Netlify, but the build there fails. I was able to to run local build and visit preview locally, but deploy in Netlify fails at build with following error:

```
[vite]: Rollup failed to resolve import "prismjs" from "/opt/build/repo/src/lib/data/blog-posts/utils.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "prismjs" from "/opt/build/repo/src/lib/data/blog-posts/utils.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
at viteWarn
```
On my local build that doesn't seem to raise any issues, and `pnpm check` only warns about `'ifYouRemoveMeTheBuildFails' is declared but its value is never read` which makes sense and shouldn't be huge issue.

Tried to google around this for a while, but wasn't able to solve yet.

**Comment by matfantinel** [comment]
@vvirta that ifYouRemoveMeTheBuildFails variable exists there to avoid this specific error, so it’s weird that it’s happening. If I recall correctly, the problem was that tree-shaking on build would not include prismjs in the final bundle, so that variable exists to “use” it so it doesn’t get removed.

I’m not able to try and reproduce that, but I guess you can try these things:

1. Modify the code so that ifYouRemoveMeTheBuildFails variable gets used, just to get rid of that warning, and see if it works;
2. Actually install prismjs as a devDependency of the project (currently it’s a dependency of mdsvex) and see if that fixes it.

Hopefully one of those work! If they do, feel free to open a PR (or at least let me know) so that the fix can be added to this template.

**Comment by vvirta** [comment]
Thank you for help. This was completely user error I believe, so nothing to fix. When I reverted back from pnpm to npm as discussed in other issue, the build started working. I'm not quite sure why build originally failed and why the error message pointed to PrismJS, but reverting back to npm made build and deploy go through.

Also cover images are working in production, so this provides at least excellent workaround to my other issue.

**Comment by vvirta** [comment]
User error. Using npm fixed the issue.

**Comment by matfantinel** [comment]
@vvirta gotcha! I never looked into pnpm (or other alternatives) so I'm not familiar with the differences between projects. Ideally, this template could work with all of them, but I don't have the time to work on that right now :(

**Comment by vvirta** [comment]
Wouldn't expect it to work :) Just really beginner error that I was having.

I really love the template and your blog as well. Thanks for sharing with the world! 👍
